version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: daily
    # Keep PR noise low
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
      include: scope
